### ISSUE TITLE
Links in top-level pages (Getting Started, Modules etc.) throw 404

### ISSUE THREAD

**Issue by execudev** [Wyamio/Wyam.Web#1]
Links in these pages are of the form: "wyam.io/getting-started**\**concepts" It looks like this is coming from _ChildPages.cshtml in the /Shared folder. Does this need to be fixed in the main Wyam repo?

``` C#
    <h3><strong><a href="/@PathHelper.RemoveExtension(childDoc.Metadata.Get<string>("FileRelative"))">@(childDoc.Metadata.Get<string>("Title", childDoc.Metadata.Get<string>("FileBase")))</a></strong></h3>
```

**Comment by daveaglick** [comment]
Yikes! I hadn't noticed that - it looks like both Chrome (which I normally use) and IE convert the slash to one that works (and as a result the links work fine in those browsers). Which browser are you using?

**Comment by daveaglick** [comment]
Thanks for reporting this! I just fixed it, all that was needed was to add `.Replace("\\", "/")` to the link location code. It happened because the "FileRelative" metadata value (really, all the file metadata) is based on the file system (which uses forward slashes) and the links need back slashes. I'm hoping to add some additional helpers soon to make creating navigation and links easier and less error-prone.

**Comment by execudev** [comment]
:thumbsup: I am using Firefox 38.0.5.
